title = "OAD Process"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = []

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-2, optimizer='COBYLA')"

[model]
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=100, iprint=2, rtol=1e-5, debug_print=True, reraise_child_analysiserror=True)"
    linear_solver = "om.DirectSolver()"
    [model.cycle]
        [model.cycle.subcycle]
            [model.cycle.subcycle.geometry]
                id = "fastga.geometry.alternate"
                propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
            [model.cycle.subcycle.aerodynamics_highspeed]
                id = "fastga.aerodynamics.highspeed.legacy"
                propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
                result_folder_path = "D:/tmp"
                use_openvsp = true
            [model.cycle.subcycle.aerodynamics_lowspeed]
                id = "fastga.aerodynamics.lowspeed.legacy"
                propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
                result_folder_path = "D:/tmp"
                use_openvsp = true
            [model.cycle.subcycle.weight]
                id = "fastga.weight.legacy"
                propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
            [model.cycle.subcycle.mtow]
                id = "fastga.loop.mtow"
            [model.cycle.subcycle.performance]
                id = "fastga.performances.sizing"
                propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
            [model.cycle.subcycle.tail_areas]
                id = "fastga.handling_qualities.tail_sizing"
                propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
        [model.cycle.static_margin]
            id = "fastga.handling_qualities.static_margin"
        [model.cycle.wing_position]
            id = "fastoad.loop.wing_position"
    [model.wing_area]
        id = "fastga.loop.wing_area"


[optimization]  # This section is needed only if optimization process is run
    [[optimization.design_var]]
        name = "data:geometry:fuselage:rear_length"
        lower = 2.0
        upper = 5.0

    [[optimization.objective]]
        name = "data:mission:sizing:fuel"